/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.at.pruebas;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Usuario extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3747277132330393786L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Usuario\",\"namespace\":\"com.at.pruebas\",\"fields\":[{\"name\":\"nombre\",\"type\":\"string\"},{\"name\":\"contrasena\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Usuario> ENCODER =
      new BinaryMessageEncoder<Usuario>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Usuario> DECODER =
      new BinaryMessageDecoder<Usuario>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Usuario> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Usuario> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Usuario> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Usuario>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Usuario to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Usuario from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Usuario instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Usuario fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence nombre;
   private java.lang.CharSequence contrasena;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Usuario() {}

  /**
   * All-args constructor.
   * @param nombre The new value for nombre
   * @param contrasena The new value for contrasena
   */
  public Usuario(java.lang.CharSequence nombre, java.lang.CharSequence contrasena) {
    this.nombre = nombre;
    this.contrasena = contrasena;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return nombre;
    case 1: return contrasena;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: nombre = (java.lang.CharSequence)value$; break;
    case 1: contrasena = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'nombre' field.
   * @return The value of the 'nombre' field.
   */
  public java.lang.CharSequence getNombre() {
    return nombre;
  }


  /**
   * Sets the value of the 'nombre' field.
   * @param value the value to set.
   */
  public void setNombre(java.lang.CharSequence value) {
    this.nombre = value;
  }

  /**
   * Gets the value of the 'contrasena' field.
   * @return The value of the 'contrasena' field.
   */
  public java.lang.CharSequence getContrasena() {
    return contrasena;
  }


  /**
   * Sets the value of the 'contrasena' field.
   * @param value the value to set.
   */
  public void setContrasena(java.lang.CharSequence value) {
    this.contrasena = value;
  }

  /**
   * Creates a new Usuario RecordBuilder.
   * @return A new Usuario RecordBuilder
   */
  public static com.at.pruebas.Usuario.Builder newBuilder() {
    return new com.at.pruebas.Usuario.Builder();
  }

  /**
   * Creates a new Usuario RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Usuario RecordBuilder
   */
  public static com.at.pruebas.Usuario.Builder newBuilder(com.at.pruebas.Usuario.Builder other) {
    if (other == null) {
      return new com.at.pruebas.Usuario.Builder();
    } else {
      return new com.at.pruebas.Usuario.Builder(other);
    }
  }

  /**
   * Creates a new Usuario RecordBuilder by copying an existing Usuario instance.
   * @param other The existing instance to copy.
   * @return A new Usuario RecordBuilder
   */
  public static com.at.pruebas.Usuario.Builder newBuilder(com.at.pruebas.Usuario other) {
    if (other == null) {
      return new com.at.pruebas.Usuario.Builder();
    } else {
      return new com.at.pruebas.Usuario.Builder(other);
    }
  }

  /**
   * RecordBuilder for Usuario instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Usuario>
    implements org.apache.avro.data.RecordBuilder<Usuario> {

    private java.lang.CharSequence nombre;
    private java.lang.CharSequence contrasena;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.at.pruebas.Usuario.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.nombre)) {
        this.nombre = data().deepCopy(fields()[0].schema(), other.nombre);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.contrasena)) {
        this.contrasena = data().deepCopy(fields()[1].schema(), other.contrasena);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Usuario instance
     * @param other The existing instance to copy.
     */
    private Builder(com.at.pruebas.Usuario other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.nombre)) {
        this.nombre = data().deepCopy(fields()[0].schema(), other.nombre);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.contrasena)) {
        this.contrasena = data().deepCopy(fields()[1].schema(), other.contrasena);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'nombre' field.
      * @return The value.
      */
    public java.lang.CharSequence getNombre() {
      return nombre;
    }


    /**
      * Sets the value of the 'nombre' field.
      * @param value The value of 'nombre'.
      * @return This builder.
      */
    public com.at.pruebas.Usuario.Builder setNombre(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.nombre = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'nombre' field has been set.
      * @return True if the 'nombre' field has been set, false otherwise.
      */
    public boolean hasNombre() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'nombre' field.
      * @return This builder.
      */
    public com.at.pruebas.Usuario.Builder clearNombre() {
      nombre = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'contrasena' field.
      * @return The value.
      */
    public java.lang.CharSequence getContrasena() {
      return contrasena;
    }


    /**
      * Sets the value of the 'contrasena' field.
      * @param value The value of 'contrasena'.
      * @return This builder.
      */
    public com.at.pruebas.Usuario.Builder setContrasena(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.contrasena = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'contrasena' field has been set.
      * @return True if the 'contrasena' field has been set, false otherwise.
      */
    public boolean hasContrasena() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'contrasena' field.
      * @return This builder.
      */
    public com.at.pruebas.Usuario.Builder clearContrasena() {
      contrasena = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Usuario build() {
      try {
        Usuario record = new Usuario();
        record.nombre = fieldSetFlags()[0] ? this.nombre : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.contrasena = fieldSetFlags()[1] ? this.contrasena : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Usuario>
    WRITER$ = (org.apache.avro.io.DatumWriter<Usuario>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Usuario>
    READER$ = (org.apache.avro.io.DatumReader<Usuario>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.nombre);

    out.writeString(this.contrasena);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.nombre = in.readString(this.nombre instanceof Utf8 ? (Utf8)this.nombre : null);

      this.contrasena = in.readString(this.contrasena instanceof Utf8 ? (Utf8)this.contrasena : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.nombre = in.readString(this.nombre instanceof Utf8 ? (Utf8)this.nombre : null);
          break;

        case 1:
          this.contrasena = in.readString(this.contrasena instanceof Utf8 ? (Utf8)this.contrasena : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










